repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        name: check added large files
        args: ['--maxkb=100']

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black
        language: python
        entry: black
        types: [python]
        args: ["--config", "pyproject.toml"]
        require_serial: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: python
        types_or: [python, pyi]
        args: ["--fix", "--config", "pyproject.toml"]
        require_serial: true


